config/routes.rb
Rails.application.routes.draw do
  root 'memos#search'
  resources :memos, only: [:new, :create, :show] do
    collection do
      get 'search'
    end
  end
end

  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

app/models/memo.rb
class Memo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController

  def search
    @memos = Memo.where('name LIKE(?)', "%#{params[:keyword]}%")
  end

  def new
    @memo = Memo.new
  end

  def create
    Memo.create(memo_params)
  end

  def show
    @memo = Memo.find(params[:id])
  end

  private
  def memo_params
    params.require(:memo).permit(:name, :age, :job, :ITCage, :bornplace, :university, :club, :hobby, :alchol, :others)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreMemo</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">FreMemo</a></h1>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>
        Copyright FreMemo 2018.
      </p>
    </footer>
  </body>
</html>

app/views/memos/create.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        投稿が完了しました。
      </h3>
    </div>
  </div>

app/views/memos/new.html.erb
<%= form_for @memo do |f| %>
 <div class="field">
   <%= f.label :name, "名前" %>
   <%= f.text_field :name %>
 </div>
 <div class="field">
   <%= f.label :age, "年齢" %>
   <%= f.text_field :age %>
 </div>
 <div class="field">
   <%= f.label :job, "仕事" %>
   <%= f.text_field :job %>
 </div>
 <div class="field">
   <%= f.text_field :ITCage %>
 </div>
 <div class="field">
   <%= f.label :bornplace, "出身地" %>
   <%= f.text_field :bornplace %>
 </div>
 <div class="field">
   <%= f.label :university, "大学" %>
   <%= f.text_field :university %>
 </div>
 <div class="field">
   <%= f.label :club, "部活" %>
   <%= f.text_field :club %>
 </div>
 <div class="field">
   <%= f.label :hobby, "趣味" %>
   <%= f.text_field :hobby %>
 </div>
 <div class="field">
   <%= f.label :alchol, "お酒" %>
   <%= f.text_field :alchol %>
 </div>
 <div class="field">
   <%= f.label :others, "その他" %>
   <%= f.text_field :others %>
 </div>
 <div class="actions">
   <%= f.submit :"新規登録" %>
 </div>
<% end %>

app/views/memos/search.html.erb
<h2>(i)検索</h2>
 <div id="form5">
  <%= form_tag('/memos/search', method: :get) do %>
  <input id="sbox5" name="keyword" type="text" placeholder="名前 or 苗字　カタカナ" />
  <input id="sbtn5" type="submit" value="検索" />
  <% end %>
 </div>
<h2>(ii)新規入力</h2>
 <%= link_to '新規入力はクリック', "/memos/new", method: :get %>

<h2>検索結果</h2>
<% @memos.each do |memo| %>
 <%= link_to memo_path(memo), method: :get do %>
  <%= memo.name %>
 <% end %>
<% end %>

app/views/memos/show.html.erb
<div>
  <span>名前</span>　<%= @memo.name %>
</div>